### ISSUE TITLE
bufr2synop cant open bufr tables

### ISSUE THREAD

**Issue by ilblog** [gbvalor/bufr2synop#3]
Hi

First of all, thank you very much for creating and publishing this nice piece of software.
I have heroically compiled bufr2synop under OS X, but I am unable to make it run.

I use `bufr2synop -V -t /usr/local/lib/bufrtables/ -i 20160530104540_ISSH16_EGRR_301000.bufr` command, where bufrtables dir contains all ECMWF bufr tables. 

The result is 

```
 open error on /home/ma/emos/tables/bufr/text/000396/B0000000000000022000.TXT
KERR=61
Unable to open table C file '/Users/ivo/utils/bufrdump/mastertables/C0000000000000019000.TXT'
Cannot read C Table  File
```

trying to find the bug myself, I have ended on a fact, that I was not able to locate `/home/ma/emos/` string in the source codes. 

Any help would be highly appreciated

**Comment by jdkloe** [comment]
This path actually is hardcoded in the fortran code of the ECMWF bufr library software. It is used if you do not specify the environment setting BUFR_TABLES to point the software to the location of the BUFR tables. I'm nor sure if bufr2synop should set this for you, or how this is handled on other platforms.

**Comment by ilblog** [comment]
Thank you for help
