### ISSUE TITLE
Compilation error ...

### ISSUE THREAD

**Issue by Mto05** [gbvalor/bufr2synop#5]
Hi,

I have a conpilation error but i don't find the provenance :

`//usr/local/lib/libbufr.a(buevar.o): In function `buevar_':
buevar.F:(.text+0xa8b): undefined reference to `emosnum_'
//usr/local/lib/libbufr.a(buexs4.o): In function `buexs4_':
buexs4.F:(.text+0x9f7): undefined reference to `gbyte_'
buexs4.F:(.text+0xbca): undefined reference to `gbyte_'
buexs4.F:(.text+0xc35): undefined reference to `gbyte_'
//usr/local/lib/libbufr.a(bunpck.o): In function `bunpck_':
bunpck.F:(.text+0x48): undefined reference to `gbyte_'
//usr/local/lib/libbufr.a(bunpks.o): In function `bunpks_':
bunpks.F:(.text+0x5b): undefined reference to `gbytes_'
//usr/local/lib/libbufr.a(bupks.o): In function `bupks_':
bupks.F:(.text+0x7b): undefined reference to `sbytes_'
//usr/local/lib/libbufr.a(burqc.o): In function `burqc_':
burqc.F:(.text+0x10dc): undefined reference to `gbyte_'
burqc.F:(.text+0x2503): undefined reference to `gbyte_'
//usr/local/lib/libbufr.a(burquc.o): In function `burquc_':
burquc.F:(.text+0xe97): undefined reference to `gbyte_'
burquc.F:(.text+0x1480): undefined reference to `gbyte_'
burquc.F:(.text+0x2f73): undefined reference to `gbytes_'
//usr/local/lib/libbufr.a(busrp.o): In function `busrp_':
busrp.F:(.text+0x5a8): undefined reference to `gbyte_'
//usr/local/lib/libbufr.a(buuatb.o): In function `buuatb_':
buuatb.F:(.text+0x5bf): undefined reference to `gbyte_'
buuatb.F:(.text+0x5ed): undefined reference to `gbyte_'
buuatb.F:(.text+0x7ca): undefined reference to `gbyte_'
//usr/local/lib/libbufr.a(buunps.o): In function `buunps_':
buunps.F:(.text+0x8d): undefined reference to `gbytes_'
//usr/local/lib/libbufr.a(busbytesR8.o): In function `busbytesr8_':
busbytesR8.F:(.text+0x3): undefined reference to `sbytes_'
//usr/local/lib/libbufr.a(busbytesR4.o): In function `busbytesr4_':
busbytesR4.F:(.text+0x3): undefined reference to `sbytes_'
//usr/local/lib/libbufr.a(bugetbm.o): In function `bugetbm_':
bugetbm.F:(.text+0x257): undefined reference to `gbytes_'
collect2: error: ld returned 1 exit status
Makefile:422: recipe for target 'bufr2synop' failed
make[3]: *** [bufr2synop] Error 1
make[3]: Leaving directory '/home/test/bufr2synop/src/apps'
Makefile:341: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory ''/home/test/bufr2synop/src'
Makefile:386: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory ''/home/test/bufr2synop'
Makefile:317: recipe for target 'all' failed
make: *** [all] Error 2
`
Can you help me ?

I thank you in advance.

Regards.

**Comment by jdkloe** [comment]
mmm, this very much looks to me like /usr/local/lib/libbufr.a is incomplete.
A command like 'ar -t  /usr/local/lib/libbufr.a | grep emosnum' should show that the emosnum.o object file is included. In the same way you can check for the object gbyte_le.o If these are missing, than building of /usr/local/lib/libbufr.a was not correct. libbufr.a should contains several compiled c routines from the bufrdc/pbio/ source directory, and if they are missing this explains the errors you get.

**Comment by Mto05** [comment]
Hi.

I Re-Compiled libbufr with 32 bits version, instead of 64 bits version, and it's run !

Thank you for your help.

Regards.
