### ISSUE TITLE
bufrtotac segfault

### ISSUE THREAD

**Issue by acoat** [gbvalor/bufr2synop#6]
Hi,

There is a segfault in decoding the attached file using bufrtotac

Sincelery

[20180111012000_ISXX41_EGRR_110104.bufr.zip](https://github.com/gbvalor/bufr2synop/files/1622068/20180111012000_ISXX41_EGRR_110104.bufr.zip)

**Comment by gbvalor** [comment]
Sorry by this loooong reply delay.

I've just now tried with latest 0.17.0 version and did no get segfault. bufrtotac cannot translate anything to TAC because descriptor sequence is not considered. I've compiled bufr2synop with gcc 12.1

**Comment by gbvalor** [comment]
I forgot to say I've replied your pull request. 

And thank you very much for your work.

Guillermo Ballester 
gbvalor@gmail.com
