### ISSUE TITLE
Message do not begin with 'BUFR'

### ISSUE THREAD

**Issue by KashifProg** [gbvalor/bufr2synop#7]
Hi,

I have installed bufrdc library and bufr2synop successfully and was able to decode the bufr reports available under bufr2synop/example but when I download real time bufr report of Surface observation and try to decode using bufr2synop I see the error message "File do not begin with 'BUFR'" I think this is happening because the first line in real time bufr reports start with header for eg. ISMD21 OPKC 190600 and the actual bufr message starts from second line. Is there any way we can skip the first line and start decoding from second line?

Thanks,

Kashif

**Comment by gbvalor** [comment]
Sorry very much by this too long delay in reply. I was not aware of this issue list in github site. I've been always working in my local server.

With respect your advice, I will see if I can avoid this problems.

Thank you very much

**Comment by gbvalor** [comment]
Hello again

I've been reading the code and on 8 march 2022 I uploaded a patch to avoid this kind of problems. Adding '-X' flag to bufrtotac arguments it search for bufr reports inside a file, assuming this file only contains one bufr report.
