### ISSUE TITLE
Not an issue, but an idea for improvement

### ISSUE THREAD

**Issue by julars** [gbvalor/bufr2synop#8]
Hi,
Thank you for the nice routines for decoding BUFR into old fashoned human readable SYNOP telegram! However, I find downloding the NOAA bin files is a huge disadvantage as it requires to download >99% that is of no use at all. 
I have tried to download original, unaltered bufr files from elsewhere and used your bufttotac program. Running bufertotac, with the debugging flag, it says that the message does not start with ”BUFR”. To remove everything before the BUFR string is easily done with an awk script. Running bufrtotac again now gives the message that it does not end with ”7777”. So I checked the end of your example files and some bin files from NOAA, extracted with bufrnoaa, with a hex-editor and I see that my files have an extra byte at the end. If i chop this of in a script of then your bufrtotac runs smoothly and gives the desired result.
Rgds,
Judith Larson

**Comment by gbvalor** [comment]
Thank you very much by your note and sorry by this long delayed reply.

I will see if I can avoid these problems. It seems the code must to filter unwanted characters before begin and after end of the actually bufr report.

Guillermo Ballester

**Comment by gbvalor** [comment]
Hello again

As I just said in a issue before, on 8 march 2022 I uploaded a patch to avoid this kind of problems. Adding '-X' flag to bufrtotac arguments it search for bufr reports inside a file, assuming this file only contains one bufr report.
